### ISSUE TITLE
Apple store rejecting UIWebView 

### ISSUE THREAD

**Issue by yuensunn** [MOLPay/molpay-mobile-xdk-flutter-beta#3]
Currently using `molpay_mobile_xdk_flutter_beta: 0.27.0`

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

**Comment by ChiHwe** [comment]
Hi yuensunn, i am integrating with this molpay API (flutter), may i know do that are you facing the apple store rejection on the payment gateway?

**Comment by yuensunn** [comment]
Yes. I passed the appstore app review after I removed the plugin from the project.

**Comment by ChiHwe** [comment]
If so, your apple app live without payment gateway?

**Comment by yuensunn** [comment]
Currently payment gateway isn't need. In the future it needs to be integrated

**Comment by ChiHwe** [comment]
There is no Molpay support can help on it ? Please help!!!!!

**Comment by clewlb** [comment]
@yuensunn As far as we know, Apple hasn't officially announce that they will stop approving app using UIWebview, it only sends warnings as in ITMS-90809, while still approving the app. We even succeeded submitting our own apps recently without much problem except the warning. So please send the official proof of reject from Apple due to UIWebview if you received it from Apple so we can check with Apple. Please be assured that we will take immediate remedy should Apple officially stop approving apps with UIWebview.

XDK Team
